apiVersion: apps/v1
kind: Deployment
metadata:
  name: discovery-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discovery-service
  template:
    metadata:
      labels:
        app: discovery-service
    spec:
      containers:
        - name: discovery-service
          image: 897729134504.dkr.ecr.us-east-1.amazonaws.com/discovery-service:latest
          ports:
            - containerPort: 8761
---
apiVersion: v1
kind: Service
metadata:
  name: discovery-service
spec:
  selector:
    app: discovery-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8761
  env:
    - name: EUREKA_INSTANCE_HOSTNAME
      valueFrom:
          fieldRef:
            fieldPath: status.hostIP
  type: LoadBalancer
